import { sql } from "drizzle-orm";
import { pgTable, text, varchar, decimal, timestamp, index, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const invoices = pgTable("invoices", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  amount: decimal("amount", { precision: 18, scale: 8 }).notNull(),
  currency: varchar("currency", { length: 10 }).notNull(),
  asset: varchar("asset", { length: 10 }).notNull(),
  description: text("description").notNull(),
  paymentAddress: text("payment_address").notNull(),
  status: varchar("status", { length: 20 }).notNull().default("pending"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  paidAt: timestamp("paid_at"),
  expiresAt: timestamp("expires_at"),
  amountPaidAtomic: varchar("amount_paid_atomic", { length: 20 }),
  railType: varchar("rail_type", { length: 20 }),
  bolt11Invoice: text("bolt11_invoice"),
  derivedAddress: text("derived_address"),
  subaddress: text("subaddress"),
  paymentSource: varchar("payment_source", { length: 20 }),
  // Lightning Network specific fields
  lnPaymentHash: text("ln_payment_hash"),
  lnCheckingId: text("ln_checking_id"),
  // Service fee fields
  merchantId: varchar("merchant_id", { length: 100 }),
  feePolicyId: varchar("fee_policy_id"),
  feeAmountAtomic: varchar("fee_amount_atomic", { length: 30 }),
  feePercent: decimal("fee_percent", { precision: 8, scale: 4 }),
  feeForwardingStatus: varchar("fee_forwarding_status", { length: 20 }),
}, (table) => ({
  // Index for efficient Lightning Network invoice lookups
  lnCheckingIdIdx: index("ln_checking_id_idx").on(table.lnCheckingId),
}));

export const insertInvoiceSchema = createInsertSchema(invoices).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  paidAt: true,
  status: true,
}).extend({
  amount: z.string().regex(/^\d+(\.\d{1,8})?$/, "Invalid amount format"),
  currency: z.enum(["BTC", "Lightning", "XMR"]),
  asset: z.enum(["BTC", "XMR"]).optional(), // Derived from currency if not provided
  paymentAddress: z.string().optional(), // Generated by rail adapters
  description: z.string().min(1, "Description is required"),
  // Lightning Network fields (optional)
  lnPaymentHash: z.string().optional(),
  lnCheckingId: z.string().optional(),
});

export type InsertInvoice = z.infer<typeof insertInvoiceSchema>;
export type Invoice = typeof invoices.$inferSelect;

export const webhookLogs = pgTable("webhook_logs", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  invoiceId: varchar("invoice_id").notNull(),
  url: text("url").notNull(),
  status: varchar("status", { length: 20 }).notNull(), // pending, success, failed
  statusCode: varchar("status_code", { length: 10 }),
  errorMessage: text("error_message"),
  attempt: varchar("attempt", { length: 10 }).default("1"),
  retryAfter: timestamp("retry_after"), // When to retry next (for persistent queue)
  createdAt: timestamp("created_at").notNull().defaultNow(),
  lastAttemptAt: timestamp("last_attempt_at"),
  payload: text("payload"), // JSON-serialized webhook body — persisted for crash-safe retry
});

export type WebhookLog = typeof webhookLogs.$inferSelect;

export const paymentTransactions = pgTable("payment_transactions", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  invoiceId: varchar("invoice_id").notNull(),
  rail: varchar("rail", { length: 10 }),
  transactionId: text("transaction_id").notNull(),
  confirmations: varchar("confirmations", { length: 10 }).notNull(),
  blockHeight: varchar("block_height", { length: 20 }),
  confirmedAt: timestamp("confirmed_at").notNull().defaultNow(),
});

export type PaymentTransaction = typeof paymentTransactions.$inferSelect;

export const templates = pgTable("templates", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  planName: text("plan_name").notNull(),
  asset: varchar("asset", { length: 10 }).notNull(),
  amountUsd: text("amount_usd"),
  interval: varchar("interval", { length: 20 }),
  description: text("description"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const insertTemplateSchema = createInsertSchema(templates).omit({
  id: true,
  createdAt: true,
}).extend({
  planName: z.string().min(1, "Plan name is required"),
  asset: z.enum(["BTC", "Lightning", "XMR"]),
  amountUsd: z.string().regex(/^\d+(\.\d{1,8})?$/, "Invalid amount format").optional(),
  interval: z.enum(["one-time", "monthly", "yearly"]).optional(),
});

export type InsertTemplate = z.infer<typeof insertTemplateSchema>;
export type Template = typeof templates.$inferSelect;

export const paymentConfirmationSchema = z.object({
  invoiceId: z.string().uuid(),
  transactionId: z.string().min(1),
  confirmations: z.number().int().nonnegative(),
  blockHeight: z.number().int().positive().optional(),
});

// Bitcoin address derivations - persistent tracking of derived addresses
export const btcAddressDerivations = pgTable("btc_address_derivations", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  invoiceId: varchar("invoice_id").notNull().unique(),
  address: text("address").notNull(),
  derivationIndex: varchar("derivation_index", { length: 20 }).notNull(),
  derivationPath: text("derivation_path").notNull(),
  amountSats: varchar("amount_sats", { length: 20 }).notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export type BtcAddressDerivation = typeof btcAddressDerivations.$inferSelect;
export type InsertBtcAddressDerivation = {
  invoiceId: string;
  address: string;
  derivationIndex: number;
  derivationPath: string;
  amountSats: number;
};

// Bitcoin payment states - state machine tracking for payment confirmations
export const btcPaymentStates = pgTable("btc_payment_states", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  invoiceId: varchar("invoice_id").notNull().unique(),
  address: text("address").notNull(),
  state: varchar("state", { length: 20 }).notNull(), // unseen, pending, confirmed, settled
  txid: text("txid"),
  confirmations: varchar("confirmations", { length: 10 }).default("0"),
  blockHeight: varchar("block_height", { length: 20 }),
  amountSats: varchar("amount_sats", { length: 20 }),
  lastChecked: timestamp("last_checked"),
  paidAt: timestamp("paid_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export type BtcPaymentState = typeof btcPaymentStates.$inferSelect;
export type InsertBtcPaymentState = {
  invoiceId: string;
  address: string;
  state: "unseen" | "pending" | "confirmed" | "settled";
  txid?: string;
  confirmations?: number;
  blockHeight?: number;
  amountSats?: number;
};

// Fee policies - configurable service fee for licensing/SaaS model
export const feePolicies = pgTable("fee_policies", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: varchar("name", { length: 100 }).notNull(),
  merchantId: varchar("merchant_id", { length: 100 }),
  feePercent: decimal("fee_percent", { precision: 8, scale: 4 }).notNull().default("0"),
  fixedFeeAtomic: varchar("fixed_fee_atomic", { length: 30 }).notNull().default("0"),
  minFeeAtomic: varchar("min_fee_atomic", { length: 30 }).notNull().default("0"),
  maxFeeAtomic: varchar("max_fee_atomic", { length: 30 }),
  currency: varchar("currency", { length: 10 }).notNull().default("BTC"),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const insertFeePolicySchema = createInsertSchema(feePolicies).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
}).extend({
  name: z.string().min(1, "Policy name is required"),
  feePercent: z.string().regex(/^\d+(\.\d{1,4})?$/, "Invalid fee percent").optional(),
  fixedFeeAtomic: z.string().regex(/^\d+$/, "Must be a positive integer string").optional(),
  minFeeAtomic: z.string().regex(/^\d+$/, "Must be a positive integer string").optional(),
  maxFeeAtomic: z.string().regex(/^\d+$/, "Must be a positive integer string").optional().nullable(),
  currency: z.enum(["BTC", "XMR", "Lightning"]).optional(),
  active: z.boolean().optional(),
  merchantId: z.string().max(100).optional().nullable(),
});

export type InsertFeePolicy = z.infer<typeof insertFeePolicySchema>;
export type FeePolicy = typeof feePolicies.$inferSelect;

export const feeSettlements = pgTable("fee_settlements", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  currency: varchar("currency", { length: 10 }).notNull(),
  totalFeeAtomic: varchar("total_fee_atomic", { length: 30 }).notNull(),
  invoiceCount: varchar("invoice_count", { length: 10 }).notNull().default("0"),
  status: varchar("status", { length: 20 }).notNull().default("pending"),
  operatorAddress: text("operator_address"),
  merchantId: varchar("merchant_id", { length: 100 }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  paidAt: timestamp("paid_at"),
  dueAt: timestamp("due_at"),
});

export type FeeSettlement = typeof feeSettlements.$inferSelect;
export type InsertFeeSettlement = {
  currency: string;
  totalFeeAtomic: string;
  invoiceCount: number;
  status?: string;
  operatorAddress?: string;
  merchantId?: string;
  dueAt?: Date;
};
